language: cpp

sudo: required

compiler:
 - clang

env:
 - MODE=release
 - MODE=debug

before_install:
 - chmod u=rx ./scripts/travis/*.sh

install:
 - sudo ./scripts/travis/install_compiler.sh
 - sudo ./scripts/travis/install_cppcheck.sh
 - sudo ./scripts/travis/install_sfml.sh

script:
 - make static-check
 - make complete RUN_DEPEND=off MODE=$MODE

